### ISSUE TITLE
Issue on page /tutorials/installing-nixos-on-a-raspberry-pi.html

### ISSUE THREAD

**Issue by seghers** [nix-dot-dev/nix.dev#174]
Link seems to be dead:

https://github.com/nix-dot-dev/nix.dev/blob/master/source/tutorials/installing-nixos-on-a-raspberry-pi.rst#L58

https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md

Use this instead:

https://www.raspberrypi.org/documentation/computers/raspberry-pi.html#updating-the-bootloader

**Comment by domenkozar** [comment]
Fixed, thanks!
