### ISSUE TITLE
Use poetry2nix?

### ISSUE THREAD

**Issue by FRidh** [nix-dot-dev/nix.dev#21]
I would like to demonstrate https://jupyter-sphinx.readthedocs.io , however, building it won't work "out-of-the-box" because `flit` is used somewhere and `pypi2nix` does not like that.

IMO we should avoid using `pypi2nix` and use `poetry2nix` instead as that one builds upon a common and well-functioning tool, `poetry`.

Of course, if this were to move into Nixpkgs we may as well use Nixpkgs' packages.

@adisbladis I suppose when PEP 517/518 is used, we need to override and set `format` in `buildPythonPackage` or does `poetry2nix` do this automatically?

**Comment by adisbladis** [comment]
Poetry2nix defaults to `format = "pyproject"`, even for dependencies so you don't have to set `format`.

However, Poetry doesn't contain a `build-system` section for dependencies, so you're gonna have to add an override adding the `flit` build input.

**Comment by domenkozar** [comment]
https://github.com/nix-dot-dev/nix.dev/pull/156
