### ISSUE TITLE
flake.nix: m1 support

### ISSUE THREAD

**Issue by domenkozar** [nix-dot-dev/nix.dev#250]
`shell-darwin.nix` exists to workaround flakes support on m1

cc @zupo, can you paste the error why it doesn't work?

**Comment by zupo** [comment]
I don't have flakes because my system is based on 21.11 which ships with too old nix. I'll circle back to this when I upgrade to 22.05 and enable flakes.

**Comment by zupo** [comment]
I believe this can be closed. Current master works for me on my M1 machine, locally dev server serves HTML files just fine and all tests pass.
