### ISSUE TITLE
A list of repos @documentation-team needs triage permissions

### ISSUE THREAD

**Issue by olafklingt** [nix-dot-dev/nix.dev#484]
GitHub documentation team members should have triage access to these repositories:
            - https://github.com/NixOS/nixpkgs
            - https://github.com/NixOS/nix
            - https://github.com/NixOS/nixos-homepage
            - https://github.com/NixOS/nix.dev
            - https://github.com/NixOS/nixos-search
            - https://github.com/NixOS/nix-pills
            - https://github.com/NixOS/nixos-summer
            - https://github.com/NixOS/nix-book

**Comment by domenkozar** [comment]
done: https://github.com/orgs/NixOS/teams/documentation-team/repositories
