### ISSUE TITLE
Add tutorial on creating a Nix channel

### ISSUE THREAD

**Issue by lucperkins** [nix-dot-dev/nix.dev#89]
It'd be nice to have a tutorial on nix.dev dedicated to both creating and consuming your own Nix channel, preferably with a kind of "progressive" logic. Maybe something along these lines:

1. Create new channel via GitHub with a single `helloWorld` package (just a basic `default.nix`)
2. Add the channel on the command line and build the `helloWorld` package (i.e. `nix-build '<my-channel>' -A helloWorld')
3. Use the channel to do a real Nix build (i.e. to create a package that consumes `helloWorld`, maybe a Docker container or something)
4. Update the channel to expose a pinned nixpkgs
5. Update the channel again to include an overlay on the pinned nixpkgs
6. Use Niv to provide pinned access to the channel.

I'd be happy to do the work, just wanted to see if others would find this helpful. And open to suggestions on content, of course.

**Comment by domenkozar** [comment]
See #16, I think that nix-channel should not be used. I'm not using it myself, except for workstation management.

I'm aware that many bits are currently harder to manage without it, but creating state to manage Nix defeats the whole idea of what Nix tries to prevent.

Flakes are going to make things sane again, but for now we are caught in despair.

**Comment by lucperkins** [comment]
Hmmm. I guess it's just not fundamentally clear to me how you could use Nix in a larger organization with many independent Nix-backed project without using a construct like channels. But I'll do some research and see how, for example, Shopify does it.

**Comment by domenkozar** [comment]
I'm happy to help if you dig into it.

Channels only really ship source, so using git (and Niv) gets you all the benefits.

**Comment by lucperkins** [comment]
Totally agree about Git+Niv! The problem I'm trying to work around, though, is how to work in a context where you have many repos but want to pin nixpkgs across all of them and also want to provide centralized expressions, functions, etc. Channels are a great mechanism for that but I'd happily ditch channels if I could do so without losing the benefits.

**Comment by domenkozar** [comment]
In that case I recommend either a monorepo (preferred) which makes things really simple or mycompany-nixlib repo with all shared utilities and reexporting nixpkgs.

Then you can depend on mycompany-nixlib with all your repos and use some automation to keep those up to date.

Let me know if I should go into more details.

**Comment by lucperkins** [comment]
I fully agree about monorepos (:heart:) but the reality is that most orgs choose not to go that route, and polyrepo orgs are my target here. From my perspective, a channel *is* precisely the ideal mechanism for distributing mycompany-nixlib. What's your preferred mechanism?

**Comment by puffnfresh** [comment]
We have a Bitbucket repository and we do `import (fetchTarball https://bitbucket.org/atlassian-marketplace/mpac-nixpkgs/get/e6c90d3d3a7bad8b062787160747f09f71ac6c0b.tar.gz) { inherit config; }` in our projects.

**Comment by lucperkins** [comment]
@puffnfresh Okay, that makes sense, and I think furnishes basically all the advantages of channels without any of the disadvantages AFAICT. I think this pretty much solves it 🚀

**Comment by domenkozar** [comment]
Indeed - https://nix.dev/tutorials/towards-reproducibility-pinning-nixpkgs.html is an alternative to channels by managing git sources in declarative way.
